ProjectIPTFinal/gforum/forums/urls.py
from django.urls import path
from . import views

app_name = 'forums'
urlpatterns = [
    path('forums/', views.forums_list, name='list'),
    path('forums/<int:forum_id>/', views.forums_detail, name='detail'),
    path('forums/<int:forum_id>/create_topic/', views.create_topic, name='create_topic'),
    # path('forums/<int:forum_id>/topics/<int:topic_id>/', views.topic_detail, name='topic_detail'),
    path('forums/<int:forum_id>/topics/<int:topic_id>/add_comment/', views.add_comment, name='add_comment'),
    # path('<int:forum_id>/topics/<int:topic_id>/add_comment/', views.add_comment, name='add_comment'),


    ####USERLOG
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup_view, name="signup"),
    path('logout/', views.logout_view, name="logout"), 


]

ProjectIPTFinal/gforum/gforum/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from forums import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.forums_list, name='home'),
    path('', include('forums.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectIPTFinal/gforum/forums/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Forum(models.Model):
    # Forum fields and relationships
    title = models.CharField(max_length=100)
    forum_slug = models.SlugField(unique=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50] + "....."
    
    def save(self, *args, **kwargs):
        if not self.forum_slug:
            self.forum_slug = slugify(self.title)
        super(Forum, self).save(*args, **kwargs)


class Topic(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    # Topic fields and relationships
    ttitle = models.CharField(max_length=100)
    topic_slug = models.SlugField(unique=True)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    tbody = models.TextField()
    tdate = models.DateTimeField(auto_now_add=True)
    tauthor = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    def __str__(self):
        return self.ttitle
    
    def save(self, *args, **kwargs):
        if not self.topic_slug:
            self.topic_slug = slugify(self.ttitle)
        super(Topic, self).save(*args, **kwargs)

    def snippet(self):
        return self.tbody[:50] + "....."
    
    
class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='comments')
    cauthor = models.ForeignKey(User, on_delete=models.CASCADE)
    cbody = models.TextField()
    cdate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cbody

ProjectIPTFinal/gforum/forums/forms.py
from django import forms
from .models import Topic, Comment

class CreateTopicForm(forms.ModelForm):
    # comment = forms.CharField(widget=forms.Textarea, label='Comment')
    class Meta:
        model = Topic
        fields = ['ttitle', 'tbody']

class CreateCommentForm(forms.ModelForm):
    # comment = forms.CharField(widget=forms.Textarea, label='Comment')
    class Meta:
        model = Comment
        fields = ['cbody']

ProjectIPTFinal/gforum/forums/views.py
from django.db import IntegrityError
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout
from .forms import CreateTopicForm, CreateCommentForm
from .models import Forum, Topic


########################### FORUM
def forums_detail(request, forum_id):
    forum = Forum.objects.get(id=forum_id)
    topics = forum.topic_set.all().order_by('-tdate')
    return render(request, 'forums/forums_detail.html', {'forum': forum, 'topics': topics})

def forums_list(request):
    forums = Forum.objects.all().order_by('-date')
    return render(request, 'forums/forums_list.html', {'forums': forums})

######################## TOPICS
def topic_detail(request, forum_id, topic_id):
    forum = Forum.objects.get(id=forum_id)
    topic = Topic.objects.get(id=topic_id, forum=forum)
    return render(request, 'topics/topic_detail.html', {'forum': forum, 'topic': topic})

@login_required(login_url='forums:login')
def create_topic(request, forum_id):
    forum = Forum.objects.get(id=forum_id)
    if request.method == 'POST':
        form = CreateTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.forum = forum
            topic.tauthor = request.user
            topic.save()
            return redirect('forums:detail', forum_id=forum.id)
    else:
        form = CreateTopicForm()
    return render(request, 'topics/create_topic.html', {'form': form})
################ACOUNTS###################################################
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('forums:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('forums:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('forums:list')
    
@login_required(login_url='forums:login')
def add_comment(request, forum_id, topic_id):
    forum = Forum.objects.get(id=forum_id)  
    topic = Topic.objects.get(id=topic_id)
    if request.method == 'POST':
        form = CreateCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.topic = topic
            comment.cauthor = request.user 
            try:
                comment.save()
                return redirect('forums:detail', forum_id=forum_id)
            except IntegrityError:
                pass
    else:
        form = CreateCommentForm()
    return render(request, 'topics/add_comment.html', {'form': form, 'topic_id': topic_id, 'forum': forum}) 

ProjectIPTFinal/gforum/forums/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="login-form">
    <h1>LOGIN USER</h1>
    <form class="site-form" action="{% url 'forums:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" class="login-button">
    </form>
    <p>Not got an account? <a href="{% url 'forums:signup' %}">Sign Up</a></p>
    </div>

{% endblock %}

ProjectIPTFinal/gforum/forums/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="signup-form">
    <h1>SIGNUP USER</h1>
    <form class="site-form" action="{% url 'forums:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup" class="signup-button">
    </form>
    </div>
{% endblock %}

ProjectIPTFinal/gforum/forums/templates/forums/forums_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="forum-detail">
    <div class="forum">
        <h2>{{ forum.title }}</h2>
        <p>{{ forum.body }}</p>
        <p>{{ forum.date }}</p>
        <p>Created By:{{ forum.author }}</p>
    </div> 
</div>

<div class="topic-block">
<h2>Related Topics:</h2>
<ul class="forum-topic">
  {% for topic in forum.topic_set.all %}
    <h1>{{ topic.ttitle }}</h1>
    <p>{{ topic.tbody }}</p>
    <p>Created By:{{ topic.tauthor }}</p>
    
    <ul>
      {% for comment in topic.comments.all %}
        <li>
          <p>{{ comment.cbody }}</p>
          <p>Created By:{{ comment.cauthor }}</p>
        </li>
      {% empty %}
        <li>No comments yet.</li>
      {% endfor %}
    </ul>

    <a href="{% url 'forums:add_comment' forum_id=forum.id topic_id=topic.id %}">Add Comment</a>
    
  {% empty %}
    <li>No topics found.</li>
  {% endfor %}
</ul>

<a href="{% url 'forums:create_topic' forum_id=forum.id %}">Create Topic</a>
</div>
{% endblock %}

ProjectIPTFinal/gforum/forums/templates/forums/forums_list.html
{% extends 'base_layout.html'%}
{% block content %}
    <h1>Available Forums</h1>
    <div class = "forums">
        {%for forum in forums%}
            <div class="forum">
                <h2><a href = "{% url 'forums:detail' forum.id %}">{{forum.title}}</a></h2>  
                <p>{{forum.snippet}}</p>
                <p>{{forum.date}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}


ProjectIPTFinal/gforum/forums/templates/topics/add_comment.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="comment-add">
  <h2>Add Comment</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Comment" class="comment-submit">
  </form>
</div>
{% endblock %}

ProjectIPTFinal/gforum/forums/templates/topics/create_topic.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="topic-create">
  <h2>Create Topic</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="topic-submit">Create</button>
  </form>
  </div>
{% endblock %}

ProjectIPTFinal/gforum/templates/base_layout.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forums</title>
    <link rel = "stylesheet" href = "{% static 'style.css' %}">
</head>
<body>
    <div class="wrapper">
        <h1><a href="{% url 'forums:list'%}" class="logo"><img src="{% static 'logo.png' %}" ></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'forums:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="logout-button">Logout</button>
                    </form>
                </li>
                {% else %}
                <li><a href="{% url 'forums:login' %}" class="signin">Sign In</a></li>
                {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

ProjectIPTFinal/gforum/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    <h1>Hello World</h1>
</body>
</html>